name: 'Dependency Review'

on:
  workflow_call:
    inputs:
      timeout-minutes:
        description: 'Optional override for larger builds'
        default: 20
        required: false
        type: number
    secrets:
      DATADOG_API_KEY:
        required: true  

permissions:
  contents: write
  pull-requests: write
  statuses: write

env:
  STATUS_NAME: 'ProdSec - Dependency Review'

jobs:
  dependency-review:
    name: Dependency Review
  #  if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
      - name: Validate Input (timeout-minutes)
        if: ${{ inputs.timeout-minutes > 99 }}
        shell: bash
        run: |
          echo "Invalid input (timeout-minutes), maximum value is 99"
          exit 1

      - name: Capture start time
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV
        shell: bash
        
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Dependency Review       
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          fail-on-scopes: runtime
          comment-summary-in-pr: always
          show-openssf-scorecard: false
          license-check: false
      - name: Update commit status
        if: always()
        uses: hyperwallet/public-security-workflows/.github/actions/commit-status@main
        with:
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
          description: ${{ job.status == 'success' && 'Dependency review completed successfully.' || 'Dependency review failed.' }}
          context: ${{ env.STATUS_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: DataDog
        uses: hyperwallet/public-security-workflows/datadog@datadog
        with:
          SOURCE: "Dependabot"
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          BU_NAME: "Chargehound"
          start_time: ${{ env.start_time }}
          OUTCOME: "${{ steps.dependabot.outcome }}"
        if: always()    

